name: first

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Print Date
        run: date
  windows:
    runs-on: windows-latest
    steps:
      - name: Print Date
        run: date
  macos:
    runs-on: macos-latest
    steps:
      - name: Print Date
        run: date
  depends:
    runs-on: ubuntu-latest
    needs: [ubuntu, windows, macos]
    steps:
      - name: Print Date
        run: date
  